/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jdeviview;

public class App {
    public void fizzMakeABuzz(String[] zzArr) {
        for (int i = 1; i <= zzArr.length; i++) {
        	if (i % 15 == 0) zzArr[i - 1] = "FizzBuzz";
        	else if (i % 5 == 0) zzArr[i - 1] = "Fizz";
        	else if (i % 3 == 0) zzArr[i - 1] = "Buzz";
        	else zzArr[i - 1] = new Integer(i).toString();
        }
    }

    public static void main(String[] args) {
        String [] zzArr = new String[46];
        new App().fizzMakeABuzz(zzArr);
        Util.printArr(zzArr);
    }
}
