/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jdeviview;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test public void fizzBuzz() {
        App classUnderTest = new App();

        String [] sampleArr = new String[20];
        classUnderTest.fizzMakeABuzz(sampleArr);
        assertEquals(sampleArr[14], "FizzBuzz", "app should have a fizz buzz moment");
        assertEquals(sampleArr[8], "Buzz", "app should have a fizz buzz moment");
        assertEquals(sampleArr[19], "Fizz", "app should have a fizz buzz moment");
    }
}
